# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1__qRNcfVdEcJ19Xfbq542H2H8GvgqXT6
"""

import pandas as pd

# 指定文件路径
file_path = '/content/賓果賓果_2024.csv'

# 读取 CSV 文件
df123 = pd.read_csv(file_path)

number_columns = [f'獎號{i}' for i in range(1, 21)]

# 找到包含指定三个号码的行
def find_next_data(df, num1, num2, num3,num4,num5):
    matches = df[
        df[number_columns].apply(lambda row: num1 in row.values and num2 in row.values and num3 in row.values and num4 in row.values and num5 in row.values, axis=1)
    ]
    next_indices = matches.index + 1
    next_data = df.iloc[next_indices].dropna(how='all')
    return next_data

# 统计下一笔资料中号码出现的频率
def top_5_frequent_numbers(next_data):
    all_numbers = next_data[number_columns].values.flatten()
    all_numbers = all_numbers[~pd.isna(all_numbers)]
    number_counts = pd.Series(all_numbers).value_counts()
    return number_counts.head(5)

# 输入三个号码
num1, num2, num3, num4, num5=

# 找到符合条件的下一笔资料
next_data = find_next_data(df123, num1, num2, num3, num4, num5)

# 统计出现最多次的前5个号码
top_5_numbers = top_5_frequent_numbers(next_data)

# 输出结果
#print("符合条件的下一笔资料：")
#print(next_data)
#print("\n出现最多次的前5个号码：")
print(top_5_numbers)

import pandas as pd

# 指定文件路径
file_path = '/content/賓果賓果_2024.csv'

# 读取 CSV 文件
df123 = pd.read_csv(file_path)

number_columns = [f'獎號{i}' for i in range(1, 21)]

# 找到包含指定三个号码的行
def find_next_data(df, num1, num2, num3):
    matches = df[
        df[number_columns].apply(lambda row: num1 in row.values and num2 in row.values and num3 in row.values, axis=1)
    ]
    next_indices = matches.index + 1
    next_data = df.iloc[next_indices].dropna(how='all')
    return next_data

# 统计下一笔资料中号码出现的频率
def top_5_frequent_numbers(next_data):
    all_numbers = next_data[number_columns].values.flatten()
    all_numbers = all_numbers[~pd.isna(all_numbers)]
    number_counts = pd.Series(all_numbers).value_counts()
    return number_counts.head(5)

# 输入三个号码
num1, num2, num3 =

# 找到符合条件的下一笔资料
next_data = find_next_data(df123, num1, num2, num3)

# 统计出现最多次的前5个号码
top_5_numbers = top_5_frequent_numbers(next_data)

# 输出结果
#print("符合条件的下一笔资料：")
#print(next_data)
#print("\n出现最多次的前5个号码：")
print(top_5_numbers)

ngrok http 127.0.0.1:5000

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!mkdir -p /drive
#umount /drive
!mount --bind /content/drive/My\ Drive /drive
!mkdir -p /drive/ngrok-ssh
!mkdir -p ~/.ssh

# Commented out IPython magic to ensure Python compatibility.
!mkdir -p /drive/ngrok-ssh
# %cd /drive/ngrok-ssh
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok-stable-linux-amd64.zip
!unzip -u ngrok-stable-linux-amd64.zip
!cp /drive/ngrok-ssh/ngrok /ngrok
!chmod +x /ngrok

!/ngrok authtoken <4b5d8074bf53cfe34d84b76f934aa469>

!pip install pyngrok

import getpass

from pyngrok import ngrok, conf

print("Enter your authtoken, which can be copied from https://dashboard.ngrok.com/auth")
conf.get_default().auth_token = getpass.getpass()

# Open a TCP ngrok tunnel to the SSH server
connection_string = ngrok.connect("22", "tcp").public_url

ssh_url, port = connection_string.strip("tcp://").split(":")
print(f" * ngrok tunnel available, access with `ssh root@{ssh_url} -p{port}`")

!pip install line-bot-sdk